services:
  # API Spring Boot
  api:
    build:
      context: ./api-book
      dockerfile: Dockerfile
    container_name: api-book-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Nuxt.js
  front:
    build:
      context: ./front-book
      dockerfile: Dockerfile
    container_name: book-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./front-book:/app
      - /app/node_modules   # ðŸ”‘ volume anonyme
    environment:
      NODE_ENV: development
      NUXT_PUBLIC_API_URL: http://api:8080
    command: pnpm dev
    depends_on:
      - api
    networks:
      - app-network
      
  # Adminer for Database Management
  adminer:
    image: adminer
    container_name: Adminer
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - 8080:8080

  # Caddy Reverse Proxy
  caddy:
    image: caddy:2-alpine
    container_name: caddy-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api
    networks:
      - app-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    profiles: ["tunnel"]
    depends_on:
      - caddy
    networks:
      - app-network

volumes:
  # ollama_data:
  caddy_data:
  caddy_config:

networks:
  app-network:
    driver: bridge